"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['foo', 'add']

# %% ../nbs/00_core.ipynb #e12cbed8
def foo(): pass

# %% ../nbs/00_core.ipynb #2bf8bc28
def add(*ar: int):
    "Adding any number of arguments"
    return sum(ar)
